### ISSUE TITLE
Start implementing responsive design

### ISSUE THREAD

**Issue by RyanRussell00** [githubrai/githubrai#13]
Look into using [media queries](https://www.w3schools.com/css/css_rwd_mediaqueries.asp)

You **MUST** add this line to the `<head>` of your HTML file, **BEFORE** the `<script>` and `<link>` tags:
`<meta name="viewport" content="width=device-width, initial-scale=1.0">`
If you don't add that line, your media queries will not work.

**Comment by githubrai** [comment]
The meta tag is added.
