### ISSUE TITLE
What is "font color =" ?

### ISSUE THREAD

**Issue by RyanRussell00** [githubrai/githubrai#16]
https://github.com/githubrai/githubrai/blob/1aa179233a5b5285c460c3c49dd0ffb9c6ade44b/project.html#L57

Please move all CSS to the CSS file

**Comment by githubrai** [comment]
Corrected.

**Comment by RyanRussell00** [comment]
Please don't use any inline CSS (CSS in the HTML). Move all styling to the CSS file.
https://github.com/githubrai/githubrai/blob/92d05efbacaf5ffdf6b3be7d3bba79a329615c23/project.html#L57

**Comment by githubrai** [comment]
Fixed it.
