### ISSUE TITLE
Remove horizontal scroll on mobile view

### ISSUE THREAD

**Issue by RyanRussell00** [githubrai/githubrai#20]
When the screen is in mobile/tablet view there is a horizontal scroll. This may be caused by a div or something that is wider than the screens width.
You should never have horizontal scrolling on a website.

![image](https://user-images.githubusercontent.com/35180491/93414547-6397f380-f856-11ea-9120-b0a3eaaf8258.png)

**Comment by githubrai** [comment]
If it is the bottom horizontal scroll then it is fixed.
