### ISSUE TITLE
Cleanup CSS and HTML

### ISSUE THREAD

**Issue by RyanRussell00** [githubrai/githubrai#22]
Please go through and remove any unused or unnecessary HTML and CSS.
The goal of this is to have as little code as possible without breaking the site.
If you have lots of duplicate CSS code, maybe put them all into 1 class?
Remove any unused CSS and HTML stuff.

**Comment by githubrai** [comment]
Fixed it.

**Comment by RyanRussell00** [comment]
Change the `*` to `body`
https://github.com/githubrai/githubrai/blob/0106ec33f1712b960e55a8cf6ab12a75d3173028/style.css#L1

Remove the font-weight and font-family
https://github.com/githubrai/githubrai/blob/0106ec33f1712b960e55a8cf6ab12a75d3173028/style.css#L2

Combine `.row` and `.flex`, looks something like `.row, .flex`
https://github.com/githubrai/githubrai/blob/0106ec33f1712b960e55a8cf6ab12a75d3173028/style.css#L6

Add `height: 100%` to column1
https://github.com/githubrai/githubrai/blob/0106ec33f1712b960e55a8cf6ab12a75d3173028/style.css#L9

Combine `hobbie2` and `hobbie3`
https://github.com/githubrai/githubrai/blob/0106ec33f1712b960e55a8cf6ab12a75d3173028/style.css#L83

Combine `.contact` and `.aboutme`
https://github.com/githubrai/githubrai/blob/0106ec33f1712b960e55a8cf6ab12a75d3173028/style.css#L118

Combine the media queries
https://github.com/githubrai/githubrai/blob/0106ec33f1712b960e55a8cf6ab12a75d3173028/style.css#L123

Combine the .column1 and .column2 into 1 line
https://github.com/githubrai/githubrai/blob/0106ec33f1712b960e55a8cf6ab12a75d3173028/style.css#L124
